version: "3.3"

networks:
  default:
    external:
      name: main-with-nginx

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/app
    ports:
    - "8000:8000"

