# Generated by Django 3.1.2 on 2020-10-04 12:35

import check_save_many.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'File parent',
                'verbose_name_plural': 'File parents',
            },
        ),
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(default=check_save_many.models.get_file_name, max_length=255, verbose_name='Image name')),
                ('img', models.ImageField(upload_to='upload/images/%Y/%m/%d/', verbose_name='Image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_save_many.fileparent', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'My image',
                'verbose_name_plural': 'My images',
            },
        ),
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default=check_save_many.models.get_file_name, max_length=255, verbose_name='File name')),
                ('my_file', models.ImageField(upload_to='upload/files/%Y/%m/%d/', verbose_name='File')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_save_many.fileparent', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'My file',
                'verbose_name_plural': 'My files',
            },
        ),
    ]
