# Generated by Django 3.1.2 on 2020-10-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_save_many', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfile_parent', to='check_save_many.fileparent', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='myimage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myimage_parent', to='check_save_many.fileparent', verbose_name='Parent'),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_parent', to='check_save_many.fileparent', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Childs',
            },
        ),
    ]
